name: scp files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: gu-domains-push
      uses: jpowerj/gu-domains-push@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
        source: "docs/*"
        target: /home/jpjgeorg/public_html/
        strip_components: 1
        overwrite: true
        rm: true

